import { Box } from '@mui/material'
import Head from 'next/head'
import FirstCol from '../components/grid1/FirstCol'
import SecondCol from '../components/grid2/SecondCol'
import ThirdCol from '../components/grid3/thirdCol'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Journal page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Box  className={styles.main}>

        <Box className={styles.grid1}>
          <FirstCol />
        </Box>

      <Box className={styles.grid2}>
        <SecondCol/>
      </Box>

      <Box className={styles.grid3}>
        <ThirdCol/>
      </Box>

     </Box>
    </div>
  )
}
